export const GET_AUTOCOMPLETE_DATA = 'GET_AUTOCOMPLETE_DATA';
export const AUTOCOMPLETE_DATA_RECEIVED = 'AUTOCOMPLETE_DATA_RECEIVED';
export const ADD_ITEM_ON_PAGE = 'ADD_ITEM_ON_PAGE';
export const DELETE_ITEM = 'DELETE_ITEM';
export const TEMPERATURE_UPDATE = 'TEMPERATURE_UPDATE';